workspace 'mobidex'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'mobidex' do
  use_frameworks!

  pod 'web3swift', '~> 2.1.3'
  pod 'AppAuth', '>= 0.94'
  pod 'Bitski', '~> 0.5.0'
end
