workspace 'mobidex'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'mobidex' do
  use_frameworks!
  pod 'web3swift', '~> 0.9.0'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end
